// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/matches": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/chat/:id": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/subscription": {
    params: {};
  };
  "/welcome": {
    params: {};
  };
  "/credits-welcome": {
    params: {};
  };
  "/profile/:id": {
    params: {
      "id": string;
    };
  };
  "/purchase-credits": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/random-chat": {
    params: {};
  };
  "/spy-list": {
    params: {};
  };
  "/settings/privacy": {
    params: {};
  };
  "/settings/terms": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/auth/callback" | "/matches" | "/chat" | "/chat/:id" | "/profile" | "/profile/edit" | "/settings" | "/subscription" | "/welcome" | "/credits-welcome" | "/profile/:id" | "/purchase-credits" | "/notifications" | "/random-chat" | "/spy-list" | "/settings/privacy" | "/settings/terms" | "/privacy" | "/terms" | "/*";
  };
  "../screens/Home.tsx": {
    id: "../screens/Home";
    page: "/";
  };
  "../screens/Auth.tsx": {
    id: "../screens/Auth";
    page: "/auth";
  };
  "./routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback";
  };
  "../screens/Matches.tsx": {
    id: "../screens/Matches";
    page: "/matches";
  };
  "../screens/ChatList.tsx": {
    id: "../screens/ChatList";
    page: "/chat";
  };
  "../screens/ChatDetail.tsx": {
    id: "../screens/ChatDetail";
    page: "/chat/:id";
  };
  "../screens/Profile.tsx": {
    id: "../screens/Profile";
    page: "/profile";
  };
  "../screens/EditProfile.tsx": {
    id: "../screens/EditProfile";
    page: "/profile/edit";
  };
  "../screens/Settings.tsx": {
    id: "../screens/Settings";
    page: "/settings";
  };
  "../screens/Subscription.tsx": {
    id: "../screens/Subscription";
    page: "/subscription";
  };
  "../screens/SubscriptionWelcome.tsx": {
    id: "../screens/SubscriptionWelcome";
    page: "/welcome";
  };
  "../screens/CreditsWelcome.tsx": {
    id: "../screens/CreditsWelcome";
    page: "/credits-welcome";
  };
  "../screens/ProfilePreview.tsx": {
    id: "../screens/ProfilePreview";
    page: "/profile/:id";
  };
  "../screens/PurchaseCredits.tsx": {
    id: "../screens/PurchaseCredits";
    page: "/purchase-credits";
  };
  "../screens/Notifications.tsx": {
    id: "../screens/Notifications";
    page: "/notifications";
  };
  "../screens/RandomChat.tsx": {
    id: "../screens/RandomChat";
    page: "/random-chat";
  };
  "../screens/SpyList.tsx": {
    id: "../screens/SpyList";
    page: "/spy-list";
  };
  "../screens/Policy.tsx": {
    id: "settings-privacy";
    page: "/settings/privacy";
  } | {
    id: "settings-terms";
    page: "/settings/terms";
  } | {
    id: "privacy-policy";
    page: "/privacy";
  } | {
    id: "terms-conditions";
    page: "/terms";
  };
  "../screens/NotFound.tsx": {
    id: "../screens/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "../screens/Home": unknown;
  "../screens/Auth": unknown;
  "routes/auth.callback": typeof import("./app/./routes/auth.callback.tsx");
  "../screens/Matches": unknown;
  "../screens/ChatList": unknown;
  "../screens/ChatDetail": unknown;
  "../screens/Profile": unknown;
  "../screens/EditProfile": unknown;
  "../screens/Settings": unknown;
  "../screens/Subscription": unknown;
  "../screens/SubscriptionWelcome": unknown;
  "../screens/CreditsWelcome": unknown;
  "../screens/ProfilePreview": unknown;
  "../screens/PurchaseCredits": unknown;
  "../screens/Notifications": unknown;
  "../screens/RandomChat": unknown;
  "../screens/SpyList": unknown;
  "settings-privacy": unknown;
  "settings-terms": unknown;
  "privacy-policy": unknown;
  "terms-conditions": unknown;
  "../screens/NotFound": unknown;
};